### ISSUE TITLE
FILE_NAME_BAND_SR_4'

### ISSUE THREAD

**Issue by taras-user** [SMByC/CloudMasking#10]
The cloud masking plugin v. 21.7.15 does not work in QGIS version 3.22.0. I present the error text.
`Traceback (most recent call last):
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/core/utils.py", line 40, in wrapper
    return func(*args, **kwargs)
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/core/utils.py", line 85, in wrapper
    obj_returned = func(*args, **kwargs)
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/cloud_masking.py", line 327, in load_stack
    self.color_stack_scene = color_stack.ColorStack(self.dockwidget.mtl_path,
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/core/color_stack.py", line 61, in __init__
    self.color_bands = [
  File "/home/taras/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CloudMasking/core/color_stack.py", line 62, in <listcomp>
    os.path.join(self.input_dir, self.mtl_file['FILE_NAME_BAND_SR_' + str(N)])
KeyError: 'FILE_NAME_BAND_SR_4'`

**Comment by XavierCLL** [comment]
Hi @taras-user thanks for reporting it, 

This is not an issue related to the Qgis version, It seems more about an error in the plugin while it is setting the file bands, but I need to check that specific case...

So, which Landsat are you trying to mask?, Collection 1 or 2? where do you download it? could you send me the Landsat ID of that image?

Thanks

**Comment by taras-user** [comment]
Thank you for the quick response!
I am downloading Landsat collection 2 Level -1 (Landsat-8) from the website https://earthexplorer.usgs.gov/
LANDSAT_PRODUCT_ID = "LC08_L1TP_181028_20210321_20210401_01_T1"

**Comment by XavierCLL** [comment]
Hi @taras-user 

I've tested with both "LC08_L1TP_181028_20210321_20210401_01_T1" and "LC08_L1TP_181028_20210321_20210401_02_T1" and the cloudmasking worked well, I found and fixed a specific error maybe related bd68d8cf6cb45d66fc9860e26ff2e0f881c76b90 but your error `KeyError: 'FILE_NAME_BAND_SR_4'` seems that the MTL file was alternated or edited please check again with the original data and if the error persists please tell me in which part of the process the error appears
