### ISSUE TITLE
Issue Cloud masking

### ISSUE THREAD

**Issue by DOLP1988** [SMByC/CloudMasking#12]
Hi, I had an issue for running Cloud Masking. I don't KNow if it is because I replaced the QGIS 3.10.14 for the 3.22.13 and I unistalled the previous QGIS versions.  Following, the note that appears on screen, thanks.

Traceback (most recent call last):
File "P:\Users/D_Leon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\core\utils.py", line 40, in wrapper
return func(*args, **kwargs)
File "P:\Users/D_Leon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\core\utils.py", line 85, in wrapper
obj_returned = func(*args, **kwargs)
File "P:\Users/D_Leon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\cloud_masking.py", line 807, in process_mask
self.masking_result.do_qaband_c2(self.dockwidget.qabandc2_file, checked_items, qaband_svalues)
File "P:\Users/D_Leon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\core\cloud_filters.py", line 890, in do_qaband_c2
gdal_calc.Calc(calc="1*(numpy.all([{nfv}], axis=0)) + 10*(numpy.any([{fv}], axis=0))".format(fv=filter_values, nfv=not_filter_values),
File "P:\Users/D_Leon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\libs\gdal_calc.py", line 399, in Calc
doit(opts, None)
File "P:\Users/D_Leon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\libs\gdal_calc.py", line 131, in doit
opts.format = GetOutputDriverFor(opts.outF)
File "P:\Users/D_Leon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\libs\gdal_calc.py", line 110, in GetOutputDriverFor
print("Several drivers matching %s extension. Using %s" % (ext, drv_list[0]))
UnboundLocalError: local variable 'ext' referenced before assignment

**Comment by XavierCLL** [comment]
Hi @DOLP1988 

It is a weird error and maybe is related to a different Qgis version, try this:
1) close all Qgis instances
2) delete the plugin folder P:\Users/D_Leon/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking
3) install it again

I hope that works
Regards

**Comment by DOLP1988** [comment]
Hi @XavierCLL 
Thanks for your advice, however, this issue remains. I deleted this plugin folder and tried again, then I uninstalled the current software, checked and deleted remaining old folders of the previous unistalled QGIS versions folders in "C" disk and desktop,  rebooted the computer, and after that I installed again this QGIS version (3.22.13) and installed the plugin, but it doesn't run.
Thanks for your comments

**Comment by XavierCLL** [comment]
Hi @DOLP1988 

I think I found the issue, could you please install the following zip and test it again? (uninstall, restart Qgis and install it from zip)
[CloudMasking.zip](https://github.com/SMByC/CloudMasking/files/10148825/CloudMasking.zip)

Thanks

**Comment by DOLP1988** [comment]
Hi @XavierCLL 

Thanks for your help!
The zip file plugin worked successfully. 
Crongrats for this amazing tool.
Regards

**Comment by XavierCLL** [comment]
Thanks to you for reporting the issue and testing it!
