### ISSUE TITLE
error cloud mask/generate the cloud mask / in only area of interest

### ISSUE THREAD

**Issue by spalaciosno** [SMByC/CloudMasking#6]
Error en la opción:
generate the cloud mask / in only area of interest

![error_cloud masking](https://user-images.githubusercontent.com/39316668/109439562-d22fce80-79fc-11eb-8c57-9240dd3d898e.JPG)

Versión de Qgis 3.10.14

detalles del error:

Traceback (most recent call last):
File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\core\utils.py", line 40, in wrapper
return func(*args, **kwargs)
File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\core\utils.py", line 85, in wrapper
obj_returned = func(*args, **kwargs)
File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\cloud_masking.py", line 470, in process_mask
self.masking_result.do_blue_band(int(self.dockwidget.doubleSpinBox_BB.value()))
File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\core\cloud_filters.py", line 417, in do_blue_band
self.blue_band_for_process = self.clip(self.blue_band_file, self.blue_band_clip_file)
File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\core\cloud_filters.py", line 136, in clip
tmp_memory_file.unlink()
File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\pathlib.py", line 1266, in unlink
self._accessor.unlink(self)
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'C:\\Users\\Usuario\\AppData\\Local\\Temp\\memory_layer_aoi.gpkg'

**Comment by XavierCLL** [comment]
Gracias Santiago, otro error relacionado con los AOI, puedes probar esta actualizacion:

[CloudMasking.zip](https://github.com/SMByC/CloudMasking/files/6059896/CloudMasking.zip)

**Comment by XavierCLL** [comment]
pudiste probarlo @spalaciosno?

**Comment by spalaciosno** [comment]
Ya lo instale y lo estoy probando, no he tenido problemas hasta ahora pero voy a probarlo más para estar seguro de que no presenta problemas, gracias

**Comment by XavierCLL** [comment]
Fixed in v21.3.22
